# Part 1: entries 1-133
PART1 = {
1: {"nativeDefinition": "The fundamental, practical details of a subject; the essential core of a matter.", "japaneseMeaning": "本質的な部分、具体的な詳細", "etymology": "nit（ニット＝幼虫）とgrit（砂利）の語源説があり、砂利の中の幼虫のように細かい部分を指すとされる。", "examples": {"B": "まず全体像を説明してから、各ステップの具体的な詳細に入ります。", "C": "この番組がアニメ制作の本質的な部分まで踏み込んでいるのが本当に面白かった。", "D": "非常に細かいが重要な。非常に細かいが重要なこと。"}},
2: {"nativeDefinition": "An overused phrase or idea that has lost originality through repetition.", "japaneseMeaning": "ありきたりな、決まり文句", "etymology": "フランス語 cliché（版を打つこと）から、印刷の型から何度も刷られた表現という意味で使われるようになった。", "examples": {"B": "イタリア人の友達がパスタを食べて、アメリカ人の友達がホットドッグを食べてる。なんてありきたりなんだ。", "C": "ちょっと決まり文句だけど、自分を卑下しちゃダメ。そうすると人に利用されちゃうよ。", "D": "独創的でない。独創的でないフレーズ。"}},
3: {"nativeDefinition": "To investigate or examine something thoroughly.", "japaneseMeaning": "（何かを）深く調べる、掘り下げる", "etymology": "dig（掘る）の比喩的用法で、表面ではなく中身まで調べるイメージ。", "examples": {"B": "データを深く調べたら、収入と健康は密接に関係していることがわかった。裕福な国ほど平均寿命が長い。", "C": "問題を提起してくれてありがとう。調べて原因を突き止めます。", "D": "何かを調査する。"}},
4: {"nativeDefinition": "To succeed in doing something despite difficulties or unlikely circumstances.", "japaneseMeaning": "それでもなんとか〜する", "etymology": "manage（なんとかする）に still（それでも）が加わり、困難な状況でも達成したニュアンスを表す。", "examples": {"B": "一日中家から出てないのに、それでもなんとかスマホをなくしちゃった。もうダメだ。", "C": "15個アラームをセットしたのに、今朝もそれでもなんとか寝坊しちゃった。", "D": "それでもなんとかする。"}},
5: {"nativeDefinition": "An informal apology meaning \"my mistake\" or \"my fault.\"", "japaneseMeaning": "ごめん、俺（私）のミス", "etymology": "スラングで my bad が「自分の落ち度」を意味するようになった。バスケットボール由来説もある。", "examples": {"B": "気づいてたかわからないけど、ジャケットにコーヒーこぼしちゃった。俺のミスだから、クリーニング代出すよ。", "C": "ごめん、昨日誕生日のお祝い忘れてた。楽しかった？", "D": "私の転落。"}},
6: {"nativeDefinition": "To form a negative opinion about someone, often in a disapproving way.", "japaneseMeaning": "（人を）批判する、ジャッジする", "etymology": "judge（裁判官）が「評価する・批判する」という意味でも使われる。", "examples": {"B": "環境のためにペットボトル水をやめたけど、君が買うのは全然OK。批判してるわけじゃないよ。", "C": "朝食にアイスクリーム食べるんだ。ジャッジしないで。", "D": "誰かを否定的に見る。"}},
7: {"nativeDefinition": "To become more communicative and willing to share personal feelings or thoughts.", "japaneseMeaning": "心を開く、打ち明ける", "etymology": "open up は「閉ざされていたものを開く」という比喩で、内面をさらけ出す意味。", "examples": {"B": "本音を言うと、小学校の頃はすごく内気だった。心を開くようになって、今はおしゃべりすぎて黙れって言われる。", "C": "彼、心の奥で何か悲しんでるのが明らかだ。悩みを打ち明けてくれたらいいのに。", "D": "もっとコミュニケーションを取るようになる。"}},
8: {"nativeDefinition": "A good or best plan or approach for moving forward with a situation.", "japaneseMeaning": "（問題解決の）良い／最善の進め方", "etymology": "way forward（前進する方法）が、困難な状況からの打開策を指す。", "examples": {"B": "ずっと頭を抱えてたけど、やっと良い進め方が見つかったと思う。", "C": "問題はそんなに複雑じゃない。冷静さを保てば、最善の進め方はすぐ見つかるよ。", "D": "前進のための良い選択肢。前進のための最善の選択肢。"}},
9: {"nativeDefinition": "A person or thing that is very well known by the general public.", "japaneseMeaning": "誰もが知っている名前、 household name", "etymology": "household（家庭）＋ name（名前）で、家庭の中でも知られているほど有名という意味。", "examples": {"B": "ちょっとした豆知識だけど、ブラッド・ピットは誰もが知る有名人になる前にリーバイスのCMに出てた。", "C": "BTSが世界中で誰もが知る存在になってるの、すごくない？", "D": "非常に有名な人や物。"}},
10: {"nativeDefinition": "The smallest amount required; the absolute minimum effort or quantity.", "japaneseMeaning": "最低限、ギリギリのライン", "etymology": "bare（裸の）＋ minimum（最小）で、これ以上減らせない最小限を表す。", "examples": {"B": "彼はいつも最低限しかやらないように見えるのに、なぜか結果を出すタイプだ。", "C": "この仕事は時間が迫ってるから、とりあえず最低限やって終わらせよう。", "D": "可能な限り少ない量。"}},
11: {"nativeDefinition": "Completely; definitely; without any doubt.", "japaneseMeaning": "100％、間違いなく", "etymology": "100 percent が「完全に・間違いなく」という強調表現として使われる。", "examples": {"B": "あのコメントは皮肉付きの褒め言葉だと思う？100％そうだよ。", "C": "彼女、おかしい？100％おかしい。", "D": "間違いなく。"}},
12: {"nativeDefinition": "To believe what someone says without requiring proof.", "japaneseMeaning": "（人の）言うことを信じる", "etymology": "take one's word（人の言葉を受け取る）から、証拠なしに信じる意味。", "examples": {"B": "メディアの言うことをそのまま信じちゃダメ。自分で調べないと。", "C": "もちろん彼女の言うことを信じるよ。完全に信頼してるから。", "D": "誰かの言うことを信じる。"}},
13: {"nativeDefinition": "An approximate or rough estimate, not exact but close enough.", "japaneseMeaning": "おおよそ、だいたい", "etymology": "野球場（ballpark）の広さから、おおよその範囲内という意味で使われるようになった。", "examples": {"B": "このデータを分析して来期の売上予測を出してくれる？だいたいの見積もりでいいよ。", "C": "頭に浮かんだ最初の数字を言っただけなんだけど、実際だいたい合ってる。", "D": "おおまかな。おおまかに。"}},
14: {"nativeDefinition": "Currently fashionable or popular.", "japaneseMeaning": "今流行っている、イケてる", "etymology": "in が「流行中の」というスラング用法。ファッションや文化で「今のトレンド」と使う。", "examples": {"B": "暗号資産への投資、今めっちゃ流行ってるよ。短期利益のために乗っかる人も多いけど、俺は長期目線。", "C": "みんな家に閉じこもってなくても、Zoomはまだ流行ってると思う？", "D": "流行っている。"}},
15: {"nativeDefinition": "Being honest and direct about something, especially something difficult.", "japaneseMeaning": "率直である、はっきり言う", "etymology": "up front（前面に）から、隠さず正面から話すという意味。", "examples": {"B": "みんな醜い部分を隠そうとするけど、君は文字通り何でも率直に話す。それが強みだと思う。", "C": "彼女がやってほしいことをはっきり言ってくれないとイライラする。早く本題に入ってよ！", "D": "何かについて正直または率直である。"}},
16: {"nativeDefinition": "Not ideal but better than having nothing at all.", "japaneseMeaning": "ないよりマシ", "etymology": "better than nothing は「何もないよりはマシ」という比較表現。", "examples": {"B": "黒いシャツが欲しかったけど、グレーしかなかった。結局グレーを買った。ないよりマシかな。", "C": "違う色のメダルが欲しかったけど、メダルはメダル。ないよりマシだ。全力でプレーしたし後悔はない。", "D": "理想的ではないが、許容できる。"}},
17: {"nativeDefinition": "Alcoholic drinks, especially in informal contexts.", "japaneseMeaning": "お酒、アルコール", "etymology": "booze は17世紀から使われる俗語で、お酒全般を指す。", "examples": {"B": "お酒持ってくるの忘れたなんて信じられない。それだけの仕事だったのに！", "C": "無料のお酒がないなら、会社の飲み会に行く意味ある？", "D": "アルコール。"}},
18: {"nativeDefinition": "Said to reassure someone that there is no obligation or urgency.", "japaneseMeaning": "気にしなくていいよ、プレッシャーかけてるわけじゃない", "etymology": "no pressure は「プレッシャーをかけない」という意味の気遣いの表現。", "examples": {"B": "ところで、これ新しいインスタアカウント。フォローしなくても全然OKだよ。", "C": "プレッシャーかけてるわけじゃないんだけど、早めに返してくれる？今月ちょっと厳しくて。", "D": "ストレスを感じないで。"}},
19: {"nativeDefinition": "To eventually do something, often unintentionally or as an unplanned result.", "japaneseMeaning": "結局〜することになる、つい〜してしまう", "etymology": "end up（最終的に〜に至る）＋ doing で、意図せずそうなった結果を表す。", "examples": {"B": "また真夜中にマクドナルド食べちゃった。なんでいつもこうなるんだ。", "C": "週末はいろいろ予定してたのに、結局ソファで足を伸ばしてゴロゴロしてた。", "D": "最終的に死ぬ。"}},
20: {"nativeDefinition": "To be good enough or sufficient for a particular purpose.", "japaneseMeaning": "（基準に）足りる、通用する", "etymology": "cut it は「切る」から転じ、「基準を満たす・通用する」という意味。", "examples": {"B": "この会社では服装が適当じゃ通用しないよ。周りから常に評価されてることを忘れないで。", "C": "今日はコーヒーじゃ足りない。レッドブルが必要。", "D": "許容できる、または十分である。"}},
}
print(f"Part1 has {len(PART1)} entries")
